# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tip guide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tip guide
pod 'SideMenu'

  target 'Tip guideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tip guideUITests' do
    # Pods for testing
  end

end
